import { useState } from 'react';

export default function TravelAssistant() {
  const [query, setQuery] = useState('');
  const [response, setResponse] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!query.trim()) {
      setError('Please enter a question');
      return;
    }

    setLoading(true);
    setError(null);
    setResponse(null);
    
    try {
      const res = await fetch('http://localhost:8000/api/ask', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ question: query.trim() }),
      });
      
      if (!res || !res.ok) {
        throw new Error(`HTTP error! status: ${res?.status || 'unknown'}`);
      }
      
      const data = await res.json();
      
      if (!data.answer) {
        throw new Error('Invalid response format');
      }
      
      setResponse(data);
    } catch (error) {
      console.error('Error:', error);
      setError(error.message || 'An error occurred while processing your request');
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (e) => {
    setQuery(e.target.value);
    // Clear error when user starts typing
    if (error) {
      setError(null);
    }
  };

  const handleClearResponse = () => {
    setResponse(null);
    setError(null);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold text-center text-gray-800 mb-8">
            Travel Documentation Assistant
          </h1>
          
          <form onSubmit={handleSubmit} className="mb-8">
            <div className="flex flex-col space-y-4">
              <input
                type="text"
                value={query}
                onChange={handleInputChange}
                placeholder="Ask about travel documentation requirements..."
                className="px-6 py-4 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-lg"
                required
                data-testid="query-input"
              />
              <button
                type="submit"
                disabled={loading}
                className="px-6 py-4 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 transition duration-200 font-semibold text-lg"
                data-testid="submit-button"
              >
                {loading ? 'Processing...' : 'Ask Question'}
              </button>
            </div>
          </form>

          {error && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-6" data-testid="error-message">
              <div className="flex">
                <div className="flex-shrink-0">
                  <svg className="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
                    <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
                  </svg>
                </div>
                <div className="ml-3">
                  <h3 className="text-sm font-medium text-red-800">Error</h3>
                  <div className="mt-2 text-sm text-red-700">
                    <p>{error}</p>
                  </div>
                </div>
              </div>
            </div>
          )}

          {response && (
            <div className="bg-white rounded-xl shadow-lg p-6" data-testid="response-container">
              <div className="flex justify-between items-center mb-4">
                <h2 className="text-2xl font-semibold text-gray-800">Response</h2>
                <button
                  onClick={handleClearResponse}
                  className="text-gray-500 hover:text-gray-700 text-sm"
                  data-testid="clear-button"
                >
                  Clear
                </button>
              </div>
              <div className="prose prose-lg max-w-none">
                <p className="text-gray-700 whitespace-pre-wrap" data-testid="response-answer">
                  {response.answer}
                </p>
              </div>
              <div className="mt-4 text-sm text-gray-500" data-testid="response-model">
                Generated by {response.model}
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
