import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import TravelAssistant from '../components/TravelAssistant';

// Mock fetch globally
global.fetch = jest.fn();

describe('TravelAssistant Integration Tests', () => {
  beforeEach(() => {
    fetch.mockClear();
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('Complete User Journey', () => {
    test('complete flow: ask question -> get response -> clear response', async () => {
      const user = userEvent.setup();
      const mockResponse = {
        answer: 'For travel to Japan, you typically need:\n1. Valid passport (6+ months validity)\n2. Visa (depending on nationality)\n3. Return ticket\n4. Proof of accommodation',
        model: 'gpt-3.5-turbo'
      };

      fetch.mockResolvedValueOnce({
        ok: true,
        json: async () => mockResponse,
      });

      render(<TravelAssistant />);
      
      // Step 1: User types a question
      const input = screen.getByTestId('query-input');
      await user.type(input, 'What do I need to travel to Japan?');
      expect(input).toHaveValue('What do I need to travel to Japan?');
      
      // Step 2: User submits the form
      const submitButton = screen.getByTestId('submit-button');
      await user.click(submitButton);
      
      // Step 3: Verify loading state
      await waitFor(() => {
        expect(submitButton).toHaveTextContent('Processing...');
        expect(submitButton).toBeDisabled();
      });
      
      // Step 4: Wait for response
      await waitFor(() => {
        expect(screen.getByTestId('response-container')).toBeInTheDocument();
      });
      
      // Step 5: Verify response content
      expect(screen.getByTestId('response-answer')).toHaveTextContent(mockResponse.answer);
      expect(screen.getByTestId('response-model')).toHaveTextContent(`Generated by ${mockResponse.model}`);
      
      // Step 6: Verify button is enabled again
      expect(submitButton).toHaveTextContent('Ask Question');
      expect(submitButton).not.toBeDisabled();
      
      // Step 7: User clears the response
      const clearButton = screen.getByTestId('clear-button');
      await user.click(clearButton);
      
      // Step 8: Verify response is cleared
      expect(screen.queryByTestId('response-container')).not.toBeInTheDocument();
    });

    test('error handling flow: network error -> retry with success', async () => {
      const user = userEvent.setup();
      
      // First call fails with network error
      fetch.mockRejectedValueOnce(new Error('Network error'));
      
      // Second call succeeds
      const mockResponse = {
        answer: 'You need a valid passport and visa for Japan.',
        model: 'gpt-3.5-turbo'
      };
      fetch.mockResolvedValueOnce({
        ok: true,
        json: async () => mockResponse,
      });

      render(<TravelAssistant />);
      
      const input = screen.getByTestId('query-input');
      const submitButton = screen.getByTestId('submit-button');
      
      // First attempt - should fail
      await user.type(input, 'What documents do I need for Japan?');
      await user.click(submitButton);
      
      await waitFor(() => {
        expect(screen.getByTestId('error-message')).toBeInTheDocument();
        expect(screen.getByText('Network error')).toBeInTheDocument();
      });
      
      // Clear input and try again
      await user.clear(input);
      await user.type(input, 'What documents do I need for Japan?');
      await user.click(submitButton);
      
      // Second attempt - should succeed
      await waitFor(() => {
        expect(screen.getByTestId('response-container')).toBeInTheDocument();
        expect(screen.getByTestId('response-answer')).toHaveTextContent(mockResponse.answer);
      });
    });
  });

  describe('Multiple API Calls', () => {
    test('handles multiple sequential API calls', async () => {
      const user = userEvent.setup();
      
      const responses = [
        {
          answer: 'You need a valid passport for Japan.',
          model: 'gpt-3.5-turbo'
        },
        {
          answer: 'You need a visa for China.',
          model: 'gpt-3.5-turbo'
        }
      ];

      fetch
        .mockResolvedValueOnce({
          ok: true,
          json: async () => responses[0],
        })
        .mockResolvedValueOnce({
          ok: true,
          json: async () => responses[1],
        });

      render(<TravelAssistant />);
      
      const input = screen.getByTestId('query-input');
      const submitButton = screen.getByTestId('submit-button');
      
      // First question
      await user.type(input, 'What do I need for Japan?');
      await user.click(submitButton);
      
      await waitFor(() => {
        expect(screen.getByTestId('response-answer')).toHaveTextContent(responses[0].answer);
      });
      
      // Clear and ask second question
      const clearButton = screen.getByTestId('clear-button');
      await user.click(clearButton);
      
      await user.clear(input);
      await user.type(input, 'What do I need for China?');
      await user.click(submitButton);
      
      await waitFor(() => {
        expect(screen.getByTestId('response-answer')).toHaveTextContent(responses[1].answer);
      });
      
      // Verify both API calls were made
      expect(fetch).toHaveBeenCalledTimes(2);
    });
  });

  describe('Edge Cases', () => {
    test('handles very long input', async () => {
      const user = userEvent.setup();
      const longQuestion = 'What documents do I need for Japan? '.repeat(10);
      const mockResponse = {
        answer: 'You need a valid passport and visa for Japan.',
        model: 'gpt-3.5-turbo'
      };

      fetch.mockResolvedValueOnce({
        ok: true,
        json: async () => mockResponse,
      });

      render(<TravelAssistant />);
      
      const input = screen.getByTestId('query-input');
      const submitButton = screen.getByTestId('submit-button');
      
      await user.type(input, longQuestion);
      await user.click(submitButton);
      
      await waitFor(() => {
        expect(screen.getByTestId('response-container')).toBeInTheDocument();
      });
      
      // Verify the trimmed input was sent
      expect(fetch).toHaveBeenCalledWith('http://localhost:8000/api/ask', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ question: longQuestion.trim() }),
      });
    });

    test('handles special characters in input', async () => {
      const user = userEvent.setup();
      const specialQuestion = 'What documents do I need for Japan? 🇯🇵 日本語';
      const mockResponse = {
        answer: 'You need a valid passport and visa for Japan.',
        model: 'gpt-3.5-turbo'
      };

      fetch.mockResolvedValueOnce({
        ok: true,
        json: async () => mockResponse,
      });

      render(<TravelAssistant />);
      
      const input = screen.getByTestId('query-input');
      const submitButton = screen.getByTestId('submit-button');
      
      await user.type(input, specialQuestion);
      await user.click(submitButton);
      
      await waitFor(() => {
        expect(screen.getByTestId('response-container')).toBeInTheDocument();
      });
      
      // Check that fetch was called with the correct parameters
      expect(fetch).toHaveBeenCalledWith('http://localhost:8000/api/ask', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: expect.stringContaining('question'),
      });
    });

    test('handles rapid successive clicks', async () => {
      const user = userEvent.setup();
      const mockResponse = {
        answer: 'You need a valid passport and visa for Japan.',
        model: 'gpt-3.5-turbo'
      };

      fetch.mockResolvedValueOnce({
        ok: true,
        json: async () => mockResponse,
      });

      render(<TravelAssistant />);
      
      const input = screen.getByTestId('query-input');
      const submitButton = screen.getByTestId('submit-button');
      
      await user.type(input, 'What documents do I need for Japan?');
      
      // Click multiple times rapidly
      await user.click(submitButton);
      await user.click(submitButton);
      await user.click(submitButton);
      
      // Wait for the first call to complete
      await waitFor(() => {
        expect(screen.getByTestId('response-container')).toBeInTheDocument();
      });
      
      // Should only make one API call (button should be disabled during loading)
      expect(fetch).toHaveBeenCalledTimes(1);
    });
  });
});
